version: '3.8'

services:
  jenkins-agent:
    image: jenkins/ssh-agent:alpine-jdk17
    container_name: jenkins-agent
    ports:
      - "2200:22"
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJIHTEwCx3hIttzm7IvAjbUXXoGVs5k85oi5sOBvzxu0 root@ip-172-31-44-71"
    volumes:
      - agent-data:/home/jenkins/agent

volumes:
  agent-data:
